export const USER_GETWEATHER_SUCCESS="USER_GETWEATHER_SUCCESS"
export const USER_GETWEATHER_ERROR="USER_GETWEATHER_ERROR"
export const USER_GETWEATHER_REQUEST="USER_GETWEATHER_REQUEST"
export const USER_SET_UNIT = "USER_SET_UNIT";

